Merge Vision / Odometry branch
Team4388/2023WayOfTheRobot pull request #32
Opened 2023-02-18 21:56 UTC by Astatin3

2023-02-18 22:30 UTC, aarav18 reviewed
not done going through it yet, I need to make some more changes

2023-02-19 18:12 UTC, 66945 requested changes
Someone should integrate the Tag class instead of returning an array of objects

2023-02-21 08:36 UTC, 66945 requested changes
Looks good, but a few small changes

2023-02-21 08:36 UTC, 66945 commented on src/main/java/frc4388/robot/subsystems/Location.java
> +            //Return Limelight Position
Maybe we should add limelight implementation before merging

2023-02-21 08:36 UTC, 66945 commented on src/main/java/frc4388/robot/subsystems/Location.java
> +    final Apriltags Apriltag = new Apriltags();
Rename var, looks like a namespace later on

2023-02-21 08:36 UTC, 66945 commented on src/main/java/frc4388/robot/subsystems/Location.java
> +    public boolean isApriltag = false;
These vars are internal (so far - high level design should get discussed later) so should not be exposed

2023-02-21 08:36 UTC, 66945 commented on src/main/java/frc4388/robot/subsystems/Location.java
> +    public void reoderPrio(){
This is a really good function, but by making it public we put the responsibility of deciding when to reprioritize onto someone else, somewhere else. A function like this should be entirely encapsulated within the Location module. I have a bit of a rant on API design that is very opinionated if anyone wants to here it later. Anyway, I suggest calling when getting location and rotation.

2023-02-21 08:36 UTC, 66945 commented on src/main/java/frc4388/robot/subsystems/Apriltags.java
> +    public Object[] getApriltagPosition() {
This Object[] stuff isn't the worst but it does lose a lot of what makes a static typing system so valuable. I added a tag class above that we could use.

2023-02-21 08:36 UTC, 66945 commented on src/main/java/frc4388/robot/subsystems/Apriltags.java
> +        // return new Object[] {true,
Make sure that the prod code is what makes it into master, not the debug code.

2023-02-21 08:36 UTC, 66945 commented on src/main/java/frc4388/robot/subsystems/Apriltags.java
> +    public Object[] getApriltagRotation() {
Why are location and rotation seperate functions. I think Micheal had a good reason, but I forget what it is

2023-02-21 08:36 UTC, 66945 commented on src/main/java/frc4388/robot/subsystems/Apriltags.java
> +        // return tagTable.getEntry("IsTag").getBoolean(false);
Again, prod code vs debug code

2023-02-21 08:36 UTC, 66945 commented on src/main/java/frc4388/robot/subsystems/Location.java
> +        Object[] Rotation = {};
Combine loc and rot, use a struct instead of an object arr, and have a better default than an empty array.

2023-02-21 08:36 UTC, 66945 commented on src/main/java/frc4388/robot/subsystems/SwerveModule.java
> +    public WPI_TalonFX angleMotor;
Protected is gods gift to programmers

2023-02-21 08:36 UTC, 66945 commented on src/main/java/frc4388/robot/subsystems/Vision.java
> +public class Vision {
As much as I love my own code, this class seems redundant and outdated given that Apriltags and Location exist

2023-02-28 01:38 UTC, aarav18 requested changes
Finished updating to correct code (master version). Still need to look over/fix vision-specific code.

2023-03-01 00:07 UTC, merged